[[common-data-types]]
= Common Data Types

[#173]
== {MUST} Use common field names and semantics

There exist a variety of field types that are required in multiple
places. To achieve consistency across all API implementations, you must
use common field names and semantics whenever applicable.

[[generic-fields]]
=== Generic Fields

There are some data fields that come up again and again in API data:

* `id`: the identity of the object. If used, IDs must opaque strings and
not numbers. IDs are unique within some documented context, are stable
and don't change for a given object once assigned, and are never
recycled cross entities.
* `xyz_id`: an attribute within one object holding the identifier of
another object must use a name that corresponds to the type of the
referenced object or the relationship to the referenced object followed
by `_id` (e.g. `customer_id` not `customer_number`; `parent_node_id` for
the reference to a parent node from a child node, even if both have the
type `Node`)
* `created`: when the object was created. If used, this must be a
`date-time` construct.
* `modified`: when the object was updated. If used, this must be a
`date-time` construct.
* `type`: the kind of thing this object is. If used, the type of this
field should be a string. Types allow runtime information on the entity
provided that otherwise requires examining the Open API file.

Example JSON schema:

[source,json]
----
tree_node:
  type: object
  properties:
    id:
      description: the identifier of this node
      type: string
    created:
      description: when got this node created
      type: string
      format: 'date-time'
    modified:
      description: when got this node last updated
      type: string
      format: 'date-time'
    type:
      type: string
      enum: [ 'LEAF', 'NODE' ]
    parent_node_id:
      description: the identifier of the parent node of this node
      type: string
  example:
    id: '123435'
    created: '2017-04-12T23:20:50.52Z'
    modified: '2017-04-12T23:20:50.52Z'
    type: 'LEAF'
    parent_node_id: '534321'
----

These properties are not always strictly necessary, but making them
idiomatic allows API client developers to build up a common
understanding of Zalando's resources. There is very little utility for
API consumers in having different names or value types for these fields
across APIs.

[#174]
== {MUST} Follow Hypertext Control Conventions

APIs that provide hypertext controls (links) to interconnect API
resources must follow the conventions for naming and modeling of
hypertext controls as defined in section <<hypermedia>>.

[#175]
== {MUST} Use Problem JSON

http://tools.ietf.org/html/rfc7807[RFC 7807] defines the media type
`application/problem+json`. Operations should return that (together with
a suitable status code) when any problem occurred during processing and
you can give more details than the status code itself can supply,
whether it be caused by the client or the server (i.e. both for 4xx or
5xx errors).

A previous version of this guideline (before the publication of that RFC
and the registration of the media type) told to return
`application/x.problem+json` in these cases (with the same contents).
Servers for APIs defined before this change should pay attention to the
`Accept` header sent by the client and set the `Content-Type` header of
the problem response correspondingly. Clients of such APIs should accept
both media types.

APIs may define custom problems types with extension properties,
according to their specific needs.

The Open API schema definition can be found
https://zalando.github.io/problem/schema.yaml[on github]. You can
reference it by using:

[source,yaml]
----
responses:
  503:
    description: Service Unavailable
    schema:
      $ref: 'https://zalando.github.io/problem/schema.yaml#/Problem'
----

[#176]
== {MUST} Do not expose Stack Traces

Stack traces contain implementation details that are not part of an API,
and on which clients should never rely. Moreover, stack traces can leak
sensitive information that partners and third parties are not allowed to
receive and may disclose insights about vulnerabilities to attackers.
