[[general-guidelines]]
= General Guidelines

The titles are marked with the corresponding labels: {MUST},
{SHOULD}, {MAY}.

[#100]
== {MUST} Follow API First Principle

As mentioned in the introduction, API First is one of our architectural
and engineering principles. In a nutshell API First requires two
aspects:

* define APIs outside the code first using a standard specification
language
* get early review feedback from peers and client developers

By defining APIs outside the code, we want to facilitate early review
feedback and also a development discipline that focus service interface
design on...

* profound understanding of the domain and required functionality
* generalized business entities / resources, i.e. avoidance of use case
specific APIs
* clear separation of WHAT vs. HOW concerns, i.e. abstraction from
implementation aspects — APIs should be stable even if we replace
complete service implementation including its underlying technology
stack

Moreover, API definitions with standardized specification format also
facilitate...

* single source of truth for the API specification; it is a crucial part
of a contract between service provider and client users
* infrastructure tooling for API discovery, API GUIs, API documents,
automated quality checks

Applying API First design requires following the guidance in this standard,
and validating it with early and consistent peer review. Peer review is
important for us to get high quality APIs, to enable architectural and
design alignment and to supported development of client applications
decoupled from service provider engineering life cycle.

It is important to learn that API First is *not in conflict with the
agile development principles* that we follow. Service applications should
evolve incrementally — and so too should APIs. Of course, our API specification
will and should evolve iteratively in different cycles; however, each
starting with draft status and _early_ team and peer review feedback.
API may change and profit from implementation concerns and automated
testing feedback. API evolution during development life cycle may
include breaking changes for not yet productive features and as long as
we have aligned the changes with the clients. Hence, API First does
_not_ mean that you must have 100% domain and requirement understanding
and can never produce code before you have defined the complete API and
get it confirmed by peer review. On the other hand, API First obviously
is in conflict with the bad practice of publishing API definition and
asking for peer review after the service integration or even the service
productive operation has started. It is crucial to request and get early
feedback — as early as possible, but not before the API changes are
comprehensive with focus to the next evolution step and have a certain
quality (including API Guideline compliance), already confirmed via team
internal reviews.

[#101]
== {MUST} Provide API Reference Definition

Using the standard (to be defined at a programme level) for API documentation,
APIs must be fully documented (including meaning and commentary, not solely
specification and conformity).

The specification of an API in this way will be referred to as the API
Reference Definition.

[#102]
== {SHOULD} Provide User Manual Documentation

In addition to the API as Reference Definition, it’s good practice to
provide an API User Manual documentation to improve client developer
experience, especially of engineers that are less experienced in using this
API. A helpful API User Manual typically describes the following API
aspects:

* API’s scope, purpose and use cases
* concrete examples of API usage
* edge cases, error situation details and repair hints
* architecture context and major dependencies - including figures and
sequence flows

The User Manual must be posted online, using the standard API documentation
hosting approach (to be defined at a programme level).

[#103]
== {MUST} Write APIs in U.K. English
